# Generated by Django 4.2.18 on 2025-01-19 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('icon', models.ImageField(blank=True, upload_to='transaction_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_transaction_id', models.CharField(blank=True, max_length=255)),
                ('last_transaction_type', models.CharField(blank=True, max_length=255)),
                ('last_transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer_sent', 'Transfer_sent'), ('Transfer_received', 'Transfer_received')], max_length=255)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Bank', 'Bank Transfer'), ('Card', 'Debit/Credit Card'), ('Momo', 'Momo Pay')], max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('account_holder_name', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('momo_number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.transactioncategory')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='models.transaction')),
            ],
            options={
                'unique_together': {('transaction', 'category')},
            },
        ),
    ]
