# Generated by Django 4.2.18 on 2025-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer_sent', 'Transfer_sent'), ('Transfer_received', 'Transfer_received')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_transaction_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
