# Generated by Django 4.2.18 on 2025-01-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='last_transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
