# Generated by Django 4.2.18 on 2025-01-20 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0005_remove_paymentmethod_wallet_paymentmethod_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
