# Generated by Django 4.2.18 on 2025-01-20 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0006_accountdetails_name_accountdetails_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
