# Generated by Django 4.2.18 on 2025-01-22 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_accountdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='Account',
            new_name='account',
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.wallet'),
        ),
    ]
